config/routes.rb
Rostra::Engine.routes.draw do
  resources :questions do
    resources :answers
  end

  root :to => "questions#index"
end

app/models/rostra/ability.rb
module Rostra
  class Ability
    include CanCan::Ability

    attr_reader :user

    def initialize(user)
      @user = user || User.new

      if logged_in?
        can :manage, Question, :user => user
        can :manage, Answer, :user => user
      end

      can :read, :all
    end

    private

    def logged_in?
      ! user.new_record?
    end

  end
end

app/models/rostra/answer.rb
module Rostra
  class Answer < ActiveRecord::Base
    belongs_to :question
    belongs_to :user

    validates :text, :presence => true
  end
end

app/models/rostra/question.rb
module Rostra
  class Question < ActiveRecord::Base

    belongs_to :user
    has_many :answers

    acts_as_taggable

    validates :title, :presence => true, :uniqueness => true, :length => { :minimum => 15 }
    validates :user, :presence => true
    validates :tag_list, :presence => true
  end
end

app/controllers/rostra/answers_controller.rb
module Rostra
  class AnswersController < ApplicationController
    load_and_authorize_resource
    before_filter :fetch_question

    def create
      if @answer.save
        redirect_to question_path(@question, anchor: "rostra_answer_#{@answer.id}")
      else
        redirect_to question_path(@question, anchor: 'new_rostra_answer')
      end
    end

    def edit
    end

    def update
      if @answer.update_attributes(params[:answer])
        redirect_to question_path(@question, anchor: "rostra_answer_#{@answer.id}")
      else
        render :edit
      end
    end

    private

    def fetch_question
      @question = Question.find(params[:question_id])
    end
  end
end

app/controllers/rostra/application_controller.rb
module Rostra
  class ApplicationController < ActionController::Base

    helper_method :user_logged_in?

    rescue_from CanCan::AccessDenied do |exception|
      after_access_denied
    end

    # Check if a user is logged in
    #
    def user_signed_in?
      current_user
    end

    private

    # Override <tt>cancan</tt>'s default class of <tt>Ability</tt> to user <tt>Rostra::Ability</tt>.
    #
    def current_ability
      @current_ability ||= Rostra::Ability.new(current_user)
    end

    # Override this method to if finer control over what happens when <tt>cancan</tt> denies access.
    #
    def after_access_denied
      redirect_to root_url, alert: "You don't have access to view this page"
    end

  end
end

app/controllers/rostra/questions_controller.rb
module Rostra
  class QuestionsController < ApplicationController
    load_and_authorize_resource

    def index
      @questions = Question.order('created_at desc')
    end

    def show
      @answers = @question.answers
    end

    def new
    end

    def edit
    end

    def create
      if @question.save
        redirect_to questions_path, notice: 'Your question has been posted.'
      else
        render :new
      end
    end

    def update
      if @question.update_attributes(params[:question])
        redirect_to @question, notice: 'Question was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @question.destroy
      redirect_to questions_url
    end
  end
end

app/helpers/rostra/application_helper.rb
module Rostra
  module ApplicationHelper
  end
end

app/helpers/rostra/questions_helper.rb
module Rostra
  module QuestionsHelper
  end
end

app/views/layouts/rostra/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rostra</title>
  <%= stylesheet_link_tag "rostra/application" %>
  <%= javascript_include_tag "rostra/application" %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= controller_name %>" class="<%= action_name %>">
  <div id="page_wrap">
    <nav>
      <%= link_to 'Recent questions', questions_path %>
    </nav>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}", class: 'flash' %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/rostra/answers/_form.html.erb
<% @answer ||= @question.answers.build  %>

<%= simple_form_for [@question, @answer], validate: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :question_id, value: @question.id %>
  <%= f.input :text, label: 'Answer this question' %>
  <%= f.submit @answer.new_record? ? 'Answer' : 'Update' %>
<% end %>

app/views/rostra/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'rostra/shared/sidebar' %>

<div id="page_content">
  <%= render 'rostra/answers/form' %>
</div>

app/views/rostra/questions/_form.html.erb
<%= simple_form_for @question, validate: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :tag_list, label: 'Tags', hint: 'Separate tags with commas' %>
  <%= f.submit "Post your question" %>
<% end %>

app/views/rostra/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'rostra/shared/sidebar' %>

<div id="page_content">
  <%= render 'form' %>
</div>

app/views/rostra/questions/index.html.erb
<h1>Recent Questions</h1>

<%= render 'rostra/shared/sidebar' %>

<div id="page_content">
    <div id="questions">
      <% if @questions.empty? %>
        <h3>No questions have been asked.</h3>

      <% else %>

        <% @questions.each do |question| %>
          <div class="question">
            <h3 class="title"><%= link_to question.title, question %></h3>
            <cite>
              Asked by <%= question.user.name %>
              <%= link_to 'edit', edit_question_path(question) if can? :manage, question %>
            </cite>
            <div class="text">
              <% if question.details.length > 250 %>
                <%= simple_format(
                  truncate(question.details, length: 250) +
                  link_to("view more", question, class: "view_more")
                ) %>

              <% else %>
                <%= simple_format(question.details) %>
              <% end %>
            </div>
            <div class="timestamp"><%= time_ago_in_words(question.updated_at) %> ago</div>
            <div class="tags">
              Tags:
              <% question.tags.each do |tag| %>
                <%= link_to tag, "" %>
              <% end %>
            </div>
          </div>
        <% end %>

      <% end %>
    </div><!-- questions -->


</div><!--page_content-->

app/views/rostra/questions/new.html.erb
<h1>Post a new question</h1>

<%= render 'sidebar' %>

<div id="page_content">
  <%= render 'form' %>
</div>

app/views/rostra/questions/show.html.erb
<h1><%= @question.title %></h1>

<%= render 'rostra/shared/sidebar' %>

<div id="page_content">

  <div class="question">
    <h3 class="title"><%= @question.title %></h3>
    <cite>
      Asked by <%= @question.user.name %>
      <%= link_to 'edit', edit_question_path(@question) if can? :manage, @question %>
    </cite>
    <div class="text"><%= simple_format(@question.details) %></div>
    <div class="timestamp"><%= time_ago_in_words(@question.updated_at) %> ago</div>
    <div class="tags">
      Tags:
      <% @question.tags.each do |tag| %>
        <%= link_to tag, "" %>
      <% end %>
    </div>
  </div>

  <% unless @answers.empty? %>
    <h3 id="answer_count"><%= pluralize(@answers.size, 'Answer') %></h3>
    <div id="answers">
      <% @answers.each do |answer| %>
        <div class="answer" id="<%= dom_id(answer) %>">
          <cite>
            <%= answer.user.name %> says:
            <%= link_to('edit', edit_question_answer_path(@question, answer)) if can? :manage, answer %>
          </cite>
          <div class="text"><%= simple_format(answer.text) %></div>
          <div class="timestamp"><%= time_ago_in_words(answer.updated_at) %> ago</div>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <%= render 'rostra/answers/form' %>
  <% else %>
    <%= link_to "Login to answer this question", main_app.new_user_session_path %>
  <% end %>
</div><!-- page_content -->

app/views/rostra/shared/_sidebar.html.erb
<div id="sidebar">
  <% if user_signed_in? %>
    <%= link_to 'Ask a question', new_question_path, class: "button" %>
  <% else %>
    <%= link_to 'Login to ask a question', main_app.new_user_session_path, class: "button" %>
  <% end %>
</div><!--sidebar-->